# Generated by Django 4.1.1 on 2022-10-05 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(editable=False, max_length=200, unique=True)),
                ('add_info', models.TextField(blank=True, max_length=500)),
                ('rent', models.IntegerField()),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('driven', models.IntegerField()),
                ('own', models.CharField(blank=True, max_length=200)),
                ('images', models.ImageField(upload_to='photos/house')),
                ('is_available', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('category', models.CharField(default='Bike', max_length=200)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
